sudo: false
language: python
arch:
 - amd64
 - ppc64le
python:
  - "2.7"
  - "3.3"
  - "3.4"
jobs: 
  exclude:
    - arch: ppc64le
      python: 3.3
    - arch: amd64
      python: 3.3
install: pip install tox-travis
script: tox
